### ISSUE TITLE
`AbsolutePath::Parent` should not re-check the path's absoluteness

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TruePath#17]
Current implementation of `AbsolutePath::Parent` just creates a new `AbsolutePath` instance, which will perform a check for path's absoluteness (absolution?).

We should consider optimizing that case, since a parent of a known absolute path is guaranteed to be absolute itself (if it is present at all).

Perhaps introduce an private method to create instances of `AbsolutePath` unchecked?

See `TODO[#17]` in the code when implementing this.

**Comment by ronimizy** [comment]
i think that there may be a designated private constructor, that has a parameter specifying whether the absoluteness of the path should be checked, with signature like so:

```cs
private AbsolutePath(string path, bool checkAbsolutenness)
```

thus all existing constructors will invoke it with flag set to `true` and when we create a path in `Parent` property it would be set to `false`

does this solution align with your vision for the library?

**Comment by ForNeVeR** [comment]
Yeah, that sounds okay.
