### ISSUE TITLE
Get file extension only

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TruePath#42]
There should be a method to get the file extension. Let's even have `FileExtensionWithDot` and `FileExtensionNoDot` since otherwise it's quite confusing: some existing functions provide and accept the dot and some aren't (validate against Java and Kotlin implementations).

I've heard of the situation with dot-only files such as `.gitignore` being confusing, so let's think a bit more about this aspect of behavior as well.

Obviously, it should mirror the `FileNameWithoutExtension` method discussed in #41.

**Comment by Komroncube** [comment]
Hi I want to contribute my first issue, so if I understood correctly you need 2 extension methods for files to get file extension withdot and with no dot

**Comment by ForNeVeR** [comment]
Yes, I think it'd be fine to have this as an extension method (for both `LocalPath` and `AbsolutePath` for now). Since both of our `*Path` types expose the `FileName`, it should be stranghtforward to implement.

You may choose to handle the part about handling files consisting of the extension only (like `.gitignore`) by looking into alternate libraries such as `java.nio.paths.Path` and current behavior of `System.IO.Path`, but feel free to leave that part to me if you wish.

**Comment by ForNeVeR** [comment]
Sure, this is easy: let me create a new interface. See #49. Hope this will help with the implementation.

**Comment by ForNeVeR** [comment]
Regarding `.gitignore`: both .NET's `Path::GetExtension` and Kotlin's `Path.extension` agree that its extension without a dot is `gitignore`. I'll confirm this with tests.
