### ISSUE TITLE
Add `AbsolutePath.StartsWith`

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TruePath#43]
An API like `AbsolutePath.StartsWith(AbsolutePath anotherPath)` would be very useful.

**Comment by Komroncube** [comment]
what is the mission of this function? could you describe so I can imagine where to start

**Comment by ForNeVeR** [comment]
Its mission is a mirror of `LocalPath::IsPrefixOf`.

`a.IsPrefixOf(b)` should mean `b.StartsWith(a)`, and it would be great to have it for both path types (i.e. implement as an extension method on `Path<T>`).

**Comment by ForNeVeR** [comment]
Closed by #69.
