### ISSUE TITLE
Methods to get a system temp directory, create temp file, create temp folder

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/TruePath#76]
I suggest that we create the following methods:

```csharp
static class Temporary
{
  public static AbsolutePath SystemTempDirectory();
  public static AbsolutePath CreateTempFile();
  public static AbsolutePath CreateTempFolder();
}
```

This resolves several problems of the existing `Path` class in the BCL:
- in `Path`, it's too easy to mix `GetTempFileName()` and `GetTempPath()`, and these have very different semantics;
- there's no standard function to create a temp folder;
- well, obviously, the standard function doesn't operate on `TruePath` types.

**Comment by Illusion4** [comment]
Hi
I would like to work on this issue. Could you please assign it to me?

**Comment by ForNeVeR** [comment]
It is not possible to assign an issue on GitHub to anyone else other than the project owner, so for now I believe it's fine if you just leave a comment that you are working on it. No need to reassign.
